language: java 
sudo: false
env:
  - NODE_VERSION="4.1" CC=clang CXX=clang++
  - NODE_VERSION="4.0" CC=clang CXX=clang++
  - NODE_VERSION="0.12"
  - NODE_VERSION="0.11"
  - NODE_VERSION="0.10"
before_install:
  - nvm install $NODE_VERSION
before_script:
  - npm install
script:
  - npm test
notifications:
  slack: rustyhorde:qUn6626kqV2JaMsGUFLlNvJa
